### PR TITLE
Fixed birthday announcement checker

### LINKED ISSUE #38: fix birthdayAnnouncements method
Current Situation:

- birthdayAnnouncements() sends bday message for registered users only in the guild they registered in
- birthdayAnnouncements() will not send announcements in guilds with bday bot and registered user **if** the user **did not** register in that guild

Expected Situation:

- birthdayAnnoucements() should send bday messages for any registered users in any guilds with the bday bot and registered users in them.

### PR DESCRIPTION
**Pull request by EthanKvachkoff**

### CODE REVIEW

**Review by dankrzeminski32 — DISMISSED** [review]
LGTM! Good job

**Comment by dankrzeminski32** [comment]
Awaiting further testing

**Comment by EthanKvachkoff** [comment]
Ran through testing and it past all tests. It is now able to be merged:)

**Review by dankrzeminski32 — APPROVED** [review]
LGTM

**Pull request merged**
